### ISSUE TITLE
Expansion Compatibility Issue

### ISSUE THREAD

**Issue by biffdit** [Istar-Eldritch/FuelControl#1]
Hi, had an issue where I was unable to use your mod with Expansion. Expansion references a .json file that is also named settings.json.

I removed your mod and my server launched without issue. I had the same problem when I turned your mod back on.

Thank you!

`---------------------------------------------
Log D:\Pingperfect\Users\josephg\7750079\profiles\crash_2022-07-30_21-20-32.log started at 30.07. 21:20:33

------------------------------------
CHICAGO-W-351-N, 30.07 2022 21:20:33
Can't compile "Game" script module!

DayZExpansion/Book/Scripts/3_Game/dayzexpansion_book\settings\book\serverinfo\expansionbooksettingcategory.c(16): Variable name 'Settings' already used as type name`

**Comment by stephanepapin** [comment]
Same issue.

**Comment by grandmaster-ramrod** [comment]
Reporting the same issue:  
DayZExpansion/Book/Scripts/3_Game/dayzexpansion_book\settings\book\serverinfo\expansionbooksettingcategory.c(16): Variable name 'Settings' already used as type name

**Comment by Istar-Eldritch** [comment]
I'll have a look soonish. I have other things ongoing atm. I accept PRs if anyone is interested in fixing it meanwhile.

**Comment by shiryou83** [comment]
Ive just uploaded a PR to add compatibility with expansion, tried on my local server and its working without problems, i can startup the server and use the commands to see the fuel pump stats ;D

**Comment by Istar-Eldritch** [comment]
Merged and coming on the next release
