### ISSUE TITLE
Admin command erro

### ISSUE THREAD

**Issue by stephanepapin** [Istar-Eldritch/FuelControl#5]
I'm admin inside `settings.json` :

```
{
    "administrators": [76561197994644854],
    "spawn_enabled": 1,
    "spawn_interval": 1800,
    "spawn_amount": 1,
    "spawn_minimum": 10,
    "pump_car_refueling": 1,
    "pump_barrel_refueling": 1,
    "siphoning": 1,
    "siphoning_limit": 95
}
```

I've tried :
#fc station list Happy
or
#fc station list
or
#fc station add --pos 1806.062988,8958.558594 "HappyBombs"
no one work :
![image](https://user-images.githubusercontent.com/65684371/194751187-dfe40cdf-ff1d-4672-8a48-49c6ca5a7d7e.png)

**Comment by Istar-Eldritch** [comment]
The administrator array should be a string array, this is, the identifier has to be quoted:
```json
{
    "administrators": ["76561197994644854"],
    ...
}
```

Closing.
