### ISSUE TITLE
Not compatible with Expansion-Book

### ISSUE THREAD

**Issue by stephanepapin** [Istar-Eldritch/FuelControl#6]
Each time I'm trying to add FuleControl in one of my server with Expansion Book, good an error ![image](https://user-images.githubusercontent.com/65684371/198900107-4e0ada78-5df5-4812-9b53-4b480a922e48.png)

**Comment by Istar-Eldritch** [comment]
This is a duplicate of #1. Its currently fixed but waiting for a release. If I have the time It will happen very soon.
