### ISSUE TITLE
Don't worked with ExpansionBook

### ISSUE THREAD

**Issue by KOJI9IH54** [Istar-Eldritch/FuelControl#7]

**Comment by MaccaNZ97** [comment]
DayZExpansion/Book/Scripts/3_Game/dayzexpansion_book\settings\book\serverinfo\expansionbooksettingcategory.c(16): Variable name 'Settings' already used as type name

In Expansion Discord they mention about classnames should be prefixed (e.g. we prefix all our classnames with Expansion)

Note removing your mod fixes the server not starting

**Comment by Istar-Eldritch** [comment]
This is fixed in the last release.
